---
title: "Vacant City-Owned Properties in Central Brooklyn"
author: "Danylo Orlov"
date: "2025-03-03"
output:
  html_document:
    keep_md: true
  pdf_document:
    toc: true
    toc_depth: '2'
  word_document:
    toc: true
    toc_depth: '2'
---



First, let's load all necessary packages:


``` r
library(knitr)
library(dplyr)
```

```
## 
## Attaching package: 'dplyr'
```

```
## The following objects are masked from 'package:stats':
## 
##     filter, lag
```

```
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
```

``` r
library(flextable)
```


Let us first load the file:


``` r
COLP=read.csv("~/Documents/vacanthome/data/input/COLP.csv")
```

We can restirct the dataset to only include city-owned Brooklyn properties with no current use:


``` r
data_brooklyn <- COLP %>%
  filter(BOROUGH == 3 & OWNERSHIP == "C" & CATEGORY == 3)
```

Now, let's see how many vacant properties there are in Brooklyn:


``` r
data_brooklyn_s <- data_brooklyn %>%
  group_by(USE.TYPE) %>%
  summarize(number = n())
print(data_brooklyn_s)
```

```
## # A tibble: 4 × 2
##   USE.TYPE                         number
##   <chr>                             <int>
## 1 NO USE                              297
## 2 NO USE-NON RESIDENTIAL STRUCTURE     13
## 3 NO USE-VACANT LAND                  549
## 4 NO USE-WATERFRONT (ANY AGENCY)       22
```

There are 549 vacant land areas in Brooklyn, and 13 non-residential structures without any use. 

Let's now zoom in on Central Brooklyn, which I am defining to include the following community districts: 302, 303, 306, 308, 309


``` r
data_central_brooklyn <- data_brooklyn %>%
  filter(CD %in% c(302, 303, 306, 308, 309))
```

Let's save this data that includes just those five community districts:


``` r
save(data_central_brooklyn, file = "data_central_brooklyn.RData")
```

We can now summarize the data again:


``` r
data_central_brooklyn_s <- data_central_brooklyn %>%
  group_by(USE.TYPE) %>%
  summarize(number = n())
print(data_central_brooklyn_s)
```

```
## # A tibble: 4 × 2
##   USE.TYPE                         number
##   <chr>                             <int>
## 1 NO USE                              128
## 2 NO USE-NON RESIDENTIAL STRUCTURE      5
## 3 NO USE-VACANT LAND                  170
## 4 NO USE-WATERFRONT (ANY AGENCY)        1
```

There are 170 vacant land areas in Central Brooklyn, and 5 non-residential structures without any use. 

Let's now list all five non-residential structures in Central Brooklyn without any use in a nice table:


``` r
#filter and rename columns
filtered_data_buildings <- data_central_brooklyn %>%
  filter(USE.TYPE == "NO USE-NON RESIDENTIAL STRUCTURE") %>%
  select(
    `Community District` = CD, 
    `House Number` = HOUSE.NUMBER, 
    `Street Name` = STREET.NAME, 
    `Address` = ADDRESS, 
    `Parcel Name` = PARCEL.NAME, 
    `Agency` = AGENCY
  )

#create a formatted table
table_buildings <- flextable(filtered_data_buildings) %>%
  set_caption("List of Non-Residential Structures in Central Brooklyn") %>%
  autofit() 

#print the formatted table
table_buildings
```

```{=html}
<div class="tabwid"><style>.cl-0327a592{}.cl-03252a74{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-0325ff9e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-0325ffa8{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-03260912{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260913{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260914{width:2.254in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0326091c{width:2.552in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0326091d{width:3.137in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0326091e{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0326091f{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260926{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260927{width:2.254in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260928{width:2.552in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260930{width:3.137in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260931{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260932{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0326093a{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0326093b{width:2.254in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0326093c{width:2.552in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-0326093d{width:3.137in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-03260944{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0327a592'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>List of Non-Residential Structures in Central Brooklyn</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-03260912"><p class="cl-0325ff9e"><span class="cl-03252a74">Community District</span></p></th><th class="cl-03260913"><p class="cl-0325ffa8"><span class="cl-03252a74">House Number</span></p></th><th class="cl-03260914"><p class="cl-0325ffa8"><span class="cl-03252a74">Street Name</span></p></th><th class="cl-0326091c"><p class="cl-0325ffa8"><span class="cl-03252a74">Address</span></p></th><th class="cl-0326091d"><p class="cl-0325ffa8"><span class="cl-03252a74">Parcel Name</span></p></th><th class="cl-0326091e"><p class="cl-0325ffa8"><span class="cl-03252a74">Agency</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-0326091f"><p class="cl-0325ff9e"><span class="cl-03252a74">302</span></p></td><td class="cl-03260926"><p class="cl-0325ffa8"><span class="cl-03252a74">300-24</span></p></td><td class="cl-03260927"><p class="cl-0325ffa8"><span class="cl-03252a74">CADMAN PLAZA WEST</span></p></td><td class="cl-03260928"><p class="cl-0325ffa8"><span class="cl-03252a74">300-24 CADMAN PLAZA WEST</span></p></td><td class="cl-03260930"><p class="cl-0325ffa8"><span class="cl-03252a74">FOREST CITY PIERREPOINT</span></p></td><td class="cl-03260931"><p class="cl-0325ffa8"><span class="cl-03252a74">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0326091f"><p class="cl-0325ff9e"><span class="cl-03252a74">302</span></p></td><td class="cl-03260926"><p class="cl-0325ffa8"><span class="cl-03252a74">121</span></p></td><td class="cl-03260927"><p class="cl-0325ffa8"><span class="cl-03252a74">SCHERMERHORN STREET</span></p></td><td class="cl-03260928"><p class="cl-0325ffa8"><span class="cl-03252a74">121 SCHERMERHORN STREET</span></p></td><td class="cl-03260930"><p class="cl-0325ffa8"><span class="cl-03252a74">LIVINGSTON PLAZA</span></p></td><td class="cl-03260931"><p class="cl-0325ffa8"><span class="cl-03252a74">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0326091f"><p class="cl-0325ff9e"><span class="cl-03252a74">309</span></p></td><td class="cl-03260926"><p class="cl-0325ffa8"><span class="cl-03252a74">1579</span></p></td><td class="cl-03260927"><p class="cl-0325ffa8"><span class="cl-03252a74">BEDFORD AVENUE</span></p></td><td class="cl-03260928"><p class="cl-0325ffa8"><span class="cl-03252a74">1579 BEDFORD AVENUE</span></p></td><td class="cl-03260930"><p class="cl-0325ffa8"><span class="cl-03252a74">BEDFORD-UNION ARMORY</span></p></td><td class="cl-03260931"><p class="cl-0325ffa8"><span class="cl-03252a74">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-0326091f"><p class="cl-0325ff9e"><span class="cl-03252a74">306</span></p></td><td class="cl-03260926"><p class="cl-0325ffa8"><span class="cl-03252a74">299</span></p></td><td class="cl-03260927"><p class="cl-0325ffa8"><span class="cl-03252a74">DEGRAW STREET</span></p></td><td class="cl-03260928"><p class="cl-0325ffa8"><span class="cl-03252a74">299 DEGRAW STREET</span></p></td><td class="cl-03260930"><p class="cl-0325ffa8"><span class="cl-03252a74">FUTURE BROOKLYN PHILHARMONIC</span></p></td><td class="cl-03260931"><p class="cl-0325ffa8"><span class="cl-03252a74">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-03260932"><p class="cl-0325ff9e"><span class="cl-03252a74">302</span></p></td><td class="cl-0326093a"><p class="cl-0325ffa8"><span class="cl-03252a74"></span></p></td><td class="cl-0326093b"><p class="cl-0325ffa8"><span class="cl-03252a74">FOOT OF ADAM ST</span></p></td><td class="cl-0326093c"><p class="cl-0325ffa8"><span class="cl-03252a74">FOOT OF ADAM ST</span></p></td><td class="cl-0326093d"><p class="cl-0325ffa8"><span class="cl-03252a74">RED HOOK WATER POLLUTION PLANT</span></p></td><td class="cl-03260944"><p class="cl-0325ffa8"><span class="cl-03252a74">DEP</span></p></td></tr></tbody></table></div>
```


And now let's do the same for all 170 vacant land areas:


``` r
#filter and rename columns
filtered_data_land <- data_central_brooklyn %>%
  filter(USE.TYPE == "NO USE-VACANT LAND") %>%
  select(
    `Community District` = CD, 
    `House Number` = HOUSE.NUMBER, 
    `Street Name` = STREET.NAME, 
    `Address` = ADDRESS, 
    `Parcel Name` = PARCEL.NAME, 
    `Agency` = AGENCY
  )

#create a formatted table
table_land <- flextable(filtered_data_land) %>%
  set_caption("List of Vacant Land Areas in Central Brooklyn") %>%
  autofit() 

#print the formatted table
table_land
```

```{=html}
<div class="tabwid"><style>.cl-0350d7b4{}.cl-034b8318{font-family:'Helvetica';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-034cea1e{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-034cea1f{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-034cfa4a{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa54{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa55{width:2.068in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa56{width:2.196in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa57{width:3.214in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa5e{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa5f{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa60{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa61{width:2.068in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa68{width:2.196in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa69{width:3.214in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa6a{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa6b{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa72{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa73{width:2.068in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa74{width:2.196in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa75{width:3.214in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa76{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa7c{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa7d{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa7e{width:2.068in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa7f{width:2.196in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa80{width:3.214in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa86{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa87{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa88{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa89{width:2.068in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa90{width:2.196in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa91{width:3.214in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa92{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa93{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa94{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa9a{width:2.068in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa9b{width:2.196in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa9c{width:3.214in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa9d{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa9e{width:1.567in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfa9f{width:1.313in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfaa4{width:2.068in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfaa5{width:2.196in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfaa6{width:3.214in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-034cfaa7{width:0.795in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-0350d7b4'><caption style="display:table-caption;margin:0pt;text-align:center;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;"><span>List of Vacant Land Areas in Central Brooklyn</span></caption><thead><tr style="overflow-wrap:break-word;"><th class="cl-034cfa4a"><p class="cl-034cea1e"><span class="cl-034b8318">Community District</span></p></th><th class="cl-034cfa54"><p class="cl-034cea1f"><span class="cl-034b8318">House Number</span></p></th><th class="cl-034cfa55"><p class="cl-034cea1f"><span class="cl-034b8318">Street Name</span></p></th><th class="cl-034cfa56"><p class="cl-034cea1f"><span class="cl-034b8318">Address</span></p></th><th class="cl-034cfa57"><p class="cl-034cea1f"><span class="cl-034b8318">Parcel Name</span></p></th><th class="cl-034cfa5e"><p class="cl-034cea1f"><span class="cl-034b8318">Agency</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FENIMORE STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">FENIMORE STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1964</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1964 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">HALSEY STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">HALSEY STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PARK PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PARK PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">706A</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">HANCOCK STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">706A HANCOCK STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">7</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LAWRENCE STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">7 LAWRENCE STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318">TWO METROTECH CENTER URA</span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">KINGSTON AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">KINGSTON AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MONROE STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">MONROE STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1953</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">UNION STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1953 UNION STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2034</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2034 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">RALPH AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">RALPH AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1966</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1966 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">UNION STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">UNION STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa6b"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa72"><p class="cl-034cea1f"><span class="cl-034b8318">784</span></p></td><td class="cl-034cfa73"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa74"><p class="cl-034cea1f"><span class="cl-034b8318">784 MYRTLE AVENUE</span></p></td><td class="cl-034cfa75"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa76"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">17</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">BRIDGE PARK DRIVE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">17 BRIDGE PARK DRIVE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DSBS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">24</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ARLINGTON PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">24 ARLINGTON PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">BEDFORD AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">BEDFORD AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CHAUNCEY STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CHAUNCEY STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1344</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">EASTERN PARKWAY</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1344 EASTERN PARKWAY</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa7c"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa7d"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa7e"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa7f"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa80"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa86"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">EMPIRE BOULEVARD</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">EMPIRE BOULEVARD</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">HUDSON AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">HUDSON AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MONTGOMERY STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">MONTGOMERY STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2042</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2042 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">7 STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">7 STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">123</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CLARKSON AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">123 CLARKSON AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CHAUNCEY STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CHAUNCEY STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">STERLING PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">STERLING PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">VANDERBILT AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">VANDERBILT AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2012</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2012 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">BAINBRIDGE STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">BAINBRIDGE STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">224</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">SARATOGA AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">224 SARATOGA AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1992</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1992 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa6b"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa72"><p class="cl-034cea1f"><span class="cl-034b8318">798</span></p></td><td class="cl-034cfa73"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa74"><p class="cl-034cea1f"><span class="cl-034b8318">798 MYRTLE AVENUE</span></p></td><td class="cl-034cfa75"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa76"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ROGERS AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ROGERS AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CROWN STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CROWN STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">DEGRAW STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">DEGRAW STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">9 STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">9 STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">5</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">METROTECH CENTER</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">5 METROTECH CENTER</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318">METRO TECH CENTER CONCOURSE</span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">941</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PRESIDENT STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">941 PRESIDENT STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa87"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa88"><p class="cl-034cea1f"><span class="cl-034b8318">792</span></p></td><td class="cl-034cfa89"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa90"><p class="cl-034cea1f"><span class="cl-034b8318">792 MYRTLE AVENUE</span></p></td><td class="cl-034cfa91"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa92"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">DEAN STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">DEAN STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa6b"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa72"><p class="cl-034cea1f"><span class="cl-034b8318">800</span></p></td><td class="cl-034cfa73"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa74"><p class="cl-034cea1f"><span class="cl-034b8318">800 MYRTLE AVENUE</span></p></td><td class="cl-034cfa75"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa76"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">BERGEN STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">BERGEN STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">319-00</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CROWN STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">319-00 CROWN STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">681</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MARCY AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">681 MARCY AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">908</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MADISON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">908 MADISON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318">FORMER LOTS FOR TOTS PLYGROUND</span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">HANCOCK STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">HANCOCK STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2036</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2036 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2014</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2014 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">STERLING PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">STERLING PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PARK WEST</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PARK WEST</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">UTICA AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">UTICA AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CHESTER COURT</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CHESTER COURT</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2040</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2040 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">155</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">UNION STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">155 UNION STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CHAUNCEY STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CHAUNCEY STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1101-17</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PARK PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1101-17 PARK PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MADISON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">MADISON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa93"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa94"><p class="cl-034cea1f"><span class="cl-034b8318">2020-A</span></p></td><td class="cl-034cfa9a"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa9b"><p class="cl-034cea1f"><span class="cl-034b8318">2020-A FULTON STREET</span></p></td><td class="cl-034cfa9c"><p class="cl-034cea1f"><span class="cl-034b8318">SARATOGA SQUARE URA SITE#171</span></p></td><td class="cl-034cfa9d"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1962</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1962 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">NOSTRAND AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">NOSTRAND AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">UNION STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">UNION STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ST MARKS AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ST MARKS AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">920-26</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">920-26 PROSPECT PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">BREVOORT PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">BREVOORT PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">BAINBRIDGE STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">BAINBRIDGE STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">EAST RIVER</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">EAST RIVER</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ALBANY AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ALBANY AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">278</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PUTNAM AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">278 PUTNAM AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PRESIDENT STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PRESIDENT STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">KANE STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">KANE STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MACON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">MACON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">BERGEN STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">BERGEN STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa7c"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa7d"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa7e"><p class="cl-034cea1f"><span class="cl-034b8318">PUTNAM AVENUE</span></p></td><td class="cl-034cfa7f"><p class="cl-034cea1f"><span class="cl-034b8318">PUTNAM AVENUE</span></p></td><td class="cl-034cfa80"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa86"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">COLUMBIA STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">309 COLUMBIA STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">164</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">GARFIELD PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">164 GARFIELD PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa93"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa94"><p class="cl-034cea1f"><span class="cl-034b8318">2016</span></p></td><td class="cl-034cfa9a"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa9b"><p class="cl-034cea1f"><span class="cl-034b8318">2016 FULTON STREET</span></p></td><td class="cl-034cfa9c"><p class="cl-034cea1f"><span class="cl-034b8318">SARATOGA SQUARE URA SITE#171</span></p></td><td class="cl-034cfa9d"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa93"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa94"><p class="cl-034cea1f"><span class="cl-034b8318">33</span></p></td><td class="cl-034cfa9a"><p class="cl-034cea1f"><span class="cl-034b8318">QUINCY STREET</span></p></td><td class="cl-034cfa9b"><p class="cl-034cea1f"><span class="cl-034b8318">33 QUINCY STREET</span></p></td><td class="cl-034cfa9c"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa9d"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">GATES AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">GATES AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PUTNAM AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PUTNAM AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa87"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa88"><p class="cl-034cea1f"><span class="cl-034b8318">796</span></p></td><td class="cl-034cfa89"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa90"><p class="cl-034cea1f"><span class="cl-034b8318">796 MYRTLE AVENUE</span></p></td><td class="cl-034cfa91"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa92"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LEFFERTS PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LEFFERTS PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">8 STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">8 STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">KINGSTON AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">KINGSTON AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1988A</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1988A FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa87"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa88"><p class="cl-034cea1f"><span class="cl-034b8318">794</span></p></td><td class="cl-034cfa89"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa90"><p class="cl-034cea1f"><span class="cl-034b8318">794 MYRTLE AVENUE</span></p></td><td class="cl-034cfa91"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa92"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT ARMS APTS</span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">KINGSTON AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">KINGSTON AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">603</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PARK PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">603 PARK PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318">PARK PL. STATION HOUSE</span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">MTA</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1970</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1970 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LEXINGTON AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LEXINGTON AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">890</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">UNION STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">890 UNION STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1124</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1124 PROSPECT PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">199</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">COLUMBIA STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">199 COLUMBIA STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LEFFERTS PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LEFFERTS PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">BAINBRIDGE STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">BAINBRIDGE STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MONROE STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">MONROE STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">DEAN STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">DEAN STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2022</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2022 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PARK WEST</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PARK WEST</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LOUIS PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LOUIS PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">UTICA AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">UTICA AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PRESIDENT STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PRESIDENT STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">307</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">COLUMBIA STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">307 COLUMBIA STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">294</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">COLUMBIA STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">294 COLUMBIA STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa93"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa94"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa9a"><p class="cl-034cea1f"><span class="cl-034b8318">QUINCY STREET</span></p></td><td class="cl-034cfa9b"><p class="cl-034cea1f"><span class="cl-034b8318">QUINCY STREET</span></p></td><td class="cl-034cfa9c"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa9d"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">RUTLAND ROAD</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">RUTLAND ROAD</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">926</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ST MARKS AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">926 ST MARKS AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa87"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa88"><p class="cl-034cea1f"><span class="cl-034b8318">966</span></p></td><td class="cl-034cfa89"><p class="cl-034cea1f"><span class="cl-034b8318">DEKALB AVENUE</span></p></td><td class="cl-034cfa90"><p class="cl-034cea1f"><span class="cl-034b8318">966 DEKALB AVENUE</span></p></td><td class="cl-034cfa91"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa92"><p class="cl-034cea1f"><span class="cl-034b8318">HRA</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">EASTERN PARKWAY</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">EASTERN PARKWAY</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ROGERS AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ROGERS AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">910</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MADISON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">910 MADISON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318">FORMER LOTS FOR TOTS PLYGROUND</span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CHAUNCEY STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CHAUNCEY STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PUTNAM AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PUTNAM AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1968</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1968 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">EASTERN PARKWAY</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">EASTERN PARKWAY</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ST JOHNS PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ST JOHNS PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ST CHARLES PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ST CHARLES PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2020</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2020 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2024</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2024 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">DEAN STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">DEAN STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PRESIDENT STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PRESIDENT STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2026</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2026 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa6b"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa72"><p class="cl-034cea1f"><span class="cl-034b8318">786</span></p></td><td class="cl-034cfa73"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa74"><p class="cl-034cea1f"><span class="cl-034b8318">786 MYRTLE AVENUE</span></p></td><td class="cl-034cfa75"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa76"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">217</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">HART STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">217 HART STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HRA</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa93"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa94"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa9a"><p class="cl-034cea1f"><span class="cl-034b8318">QUINCY STREET</span></p></td><td class="cl-034cfa9b"><p class="cl-034cea1f"><span class="cl-034b8318">QUINCY STREET</span></p></td><td class="cl-034cfa9c"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa9d"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">406</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">NOSTRAND AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">406 NOSTRAND AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">UTICA AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">UTICA AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2018</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2018 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ST MARKS AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ST MARKS AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318">PROSPECT ARMS APTS</span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">2038</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">2038 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">VANDERBILT AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">VANDERBILT AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FLATBUSH AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">FLATBUSH AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MACON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">MACON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">494A</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">PUTNAM AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">494A PUTNAM AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ALBANY AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ALBANY AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MONTGOMERY STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">MONTGOMERY STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CARROLL STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">EASTERN PARKWAY</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">EASTERN PARKWAY</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ROGERS AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">ROGERS AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">53</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MC DOUGAL STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">53 MC DOUGAL STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa7c"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa7d"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa7e"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa7f"><p class="cl-034cea1f"><span class="cl-034b8318">MYRTLE AVENUE</span></p></td><td class="cl-034cfa80"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa86"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">LINCOLN PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">1994</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">1994 FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">302</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">IRVING PLACE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">IRVING PLACE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">MARCY AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">MARCY AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">CROWN STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">CROWN STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">306</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">SUMMIT STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">SUMMIT STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">TROY AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">TROY AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">308</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318">978</span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">ST MARKS AVENUE</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">978 ST MARKS AVENUE</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa5f"><p class="cl-034cea1e"><span class="cl-034b8318">303</span></p></td><td class="cl-034cfa60"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa61"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa68"><p class="cl-034cea1f"><span class="cl-034b8318">FULTON STREET</span></p></td><td class="cl-034cfa69"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfa6a"><p class="cl-034cea1f"><span class="cl-034b8318">HPD</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-034cfa9e"><p class="cl-034cea1e"><span class="cl-034b8318">309</span></p></td><td class="cl-034cfa9f"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfaa4"><p class="cl-034cea1f"><span class="cl-034b8318">MONTGOMERY STREET</span></p></td><td class="cl-034cfaa5"><p class="cl-034cea1f"><span class="cl-034b8318">MONTGOMERY STREET</span></p></td><td class="cl-034cfaa6"><p class="cl-034cea1f"><span class="cl-034b8318"></span></p></td><td class="cl-034cfaa7"><p class="cl-034cea1f"><span class="cl-034b8318">DCAS</span></p></td></tr></tbody></table></div>
```






